language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -r requirements.txt
  - pip install -r simulation/requirements.txt

script:
  - cd simulation/test/
  - python -m unittest discover
