language: python

python:
  - "3.6"

cache:
  pip : true
  directories:
    - $(npm config get prefix)/lib/node_modules

install:
  - pip install -r requirements.txt
  - npm install -g truffle

script:
  - python -m unittest discover
  - cd truffle
  - truffle test

notifications:
    slack: absolutelyno:husVV86h9j4IeoQTmekkK5FX
