language: python

python:
  - "3.6"

cache:
  pip : true
  directories:
    - $(npm config get prefix)/lib/node_modules

install:
  - pip install -r requirements.txt
  - npm install -g truffle

script:
  - python -m unittest discover
  - cd truffle
  - truffle test

notifications:
  slack:
    secure: O7+3riH73yFf9Ka2tK6+p9/tSFs3/NEDfyCTL7YlSZ9prtKXlcYj5vACxTtfgGrAPW+I8xmLCENw75bcUZ74Y12XXjtH+ULmScAadsRd4BtaaYYQfPa/cRjkT7MMGkc8MRo6asESMSA4uU7S5EDMUYUjHjCRSQhD3p19gA9YPmRJfXvYGl4t5/W0KhcD5it2p3McvjjlixVY3R7I1775tkx9iFrpJIi4uX1kjqtqELkchOYTym5USLWrVlstg5L+hUflvT5uQandvDY+pjKeK+tk2Yyj788tE2K9CPxzhTD1rMU7rkmBmzY6fBWivWhP+ua1RSjbl9h4IPKcxCiXt5WXfl+n/KEdg3/YbPG4xV2ABhnmHMnpzHHPWvT36SDZQxT69YDIFH87v5C8NpID4rWVZ9E4Gk496NiSRnpJ36IzFz9lOR/p76+tVlGq77wgevtsVMJkoFX243re4mnL+sEQG+79yHmLje1GADVHoz6GOEdubIH7VzFRPAGNT0BFFb2vugfChXwAQv8DVex6DqTTsoMkkLy/EaqidelkSbZcM8W7LnPy2MLIVsx/OJ9v7ypsJ370JkvaFk6DzrGBW/HftC7ANKqveUqFeoTQGDAHXVFG0ohExjthG8+sxHsw+ie+5E2n0aUL1Dj78Gyju4I8VzaqySBOu9CovGyiOHM=
