language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -r simulation/requirements.txt

script:
  - cd simulation
  - python -m unittest discover
  
notifications:
    slack: absolutelyno:husVV86h9j4IeoQTmekkK5FX
