language: python

python:
  - "3.6"

cache:
  pip : true
  directories:
    - $(npm config get prefix)/lib/node_modules

install:
  - pip install -r client/requirements.txt
  - npm install -g truffle
  - npm install -g ethereumjs-testrpc

script:
  - cd client
  - python -m unittest discover
  - cd ../truffle
  - truffle test

notifications:
    slack: absolutelyno:husVV86h9j4IeoQTmekkK5FX
